# -*- coding: utf-8 -*-
"""ClassificacaoDeTextosSpacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQ0Z7slSa8wNhhpa1TFFOHI3F1M3cYIK
"""

!pip install spacy --upgrade
!python3 -m spacy download pt_core_news_sm

import pandas as pd
import string
import spacy
import random
import seaborn as sns
import numpy as np

base_dados = pd.read_csv('/content/base_treinamento.txt', encoding = 'utf-8')

base_dados.shape

base_dados.head()

base_dados.tail()

sns.countplot(base_dados['emocao'], label = 'Contagem');









